### ISSUE TITLE
Tambahkan menu Assign Guru

### ISSUE THREAD

**Issue by billymontolalu** [rizal1919/project-app-1#18]
CRUD
buat tabel assign_guru
kolom
tanggal
foreign key guru
foreign key aktivasi
foreign key materis
status (tipe integer)
pertemuan (tipe integer)

**Comment by rizal1919** [comment]
![Screenshot (143)](https://user-images.githubusercontent.com/76481903/185755588-3b3d1589-1aa8-4f8e-bc69-913bfef49277.png)
