### ISSUE TITLE
Kolom biaya diganti dengan type number

### ISSUE THREAD

**Issue by billymontolalu** [rizal1919/project-app-1#19]

**Comment by rizal1919** [comment]
![Screenshot (151)](https://user-images.githubusercontent.com/76481903/186797715-eff97981-401a-42e7-88ca-309b512ff17a.png)
![Screenshot (152)](https://user-images.githubusercontent.com/76481903/186797719-b1e16f23-f4aa-4624-97f1-7ee980c1ce8b.png)
