### ISSUE TITLE
Bug ketika jalan dilinux

### ISSUE THREAD

**Issue by billymontolalu** [rizal1919/project-app-1#22]
Contoh file views/Login/index.blade.php

ada
@extends('layouts.main')

Harusnya "Layouts" pake L besar sesuai nama folder di view nya

**Comment by rizal1919** [comment]
![Screenshot (160)](https://user-images.githubusercontent.com/76481903/187163021-f0646af1-5204-4594-9d42-3ed27eaa86ab.png)
