### ISSUE TITLE
Penugasan Guru

### ISSUE THREAD

**Issue by billymontolalu** [rizal1919/project-app-1#24]
![Penugasan_Guru_-_Page](https://user-images.githubusercontent.com/2960998/187327547-f2774a82-a07b-4053-a81e-2ee5251a0cf9.png)
1. Penugasan Guru Tidak hanya untuk aktivasi saja, tapi untuk kurikulum juga
2. Pertemuan itu angka, dan otomatis urut sampe jumlah pertemuan habis
3. di pertemuan placeholder nya kok masih ada tulisan example@gmail.com

**Comment by rizal1919** [comment]
1. Perubahan pada pilihan dropdown hanya terdapat aktivasi dan materi terkait. Kurikulum dihilangkan
2. Pertemuan dihapus
3. Pertemuan dihapus

![Screenshot (178)](https://user-images.githubusercontent.com/76481903/189814380-b3c40182-27aa-4fc8-83ea-50dc917a7210.png)
