### ISSUE TITLE
Edit data siswa

### ISSUE THREAD

**Issue by billymontolalu** [rizal1919/project-app-1#25]
http://localhost:8000/data-siswa/update/student/1
Tombol Tambah Siswa Diganti dengan "Update"

Pergantian ini berlaku untuk semua edit data pada semua form

**Comment by rizal1919** [comment]
![Screenshot (168)](https://user-images.githubusercontent.com/76481903/189813714-abf76939-3e2e-4bce-8f81-f1b00a4824d1.png)
![Screenshot (169)](https://user-images.githubusercontent.com/76481903/189813720-ae69bdf9-6aeb-4926-ae01-1f5f678f2df5.png)
![Screenshot (171)](https://user-images.githubusercontent.com/76481903/189813721-16b8bf97-ea47-4b85-977a-663344def8f3.png)
![Screenshot (172)](https://user-images.githubusercontent.com/76481903/189813725-cafd972b-cde9-417f-98c6-1ebb3c20afe9.png)
![Screenshot (173)](https://user-images.githubusercontent.com/76481903/189813728-631cb221-b7a8-487d-9456-f9fe413f09b5.png)
![Screenshot (174)](https://user-images.githubusercontent.com/76481903/189813730-d3baee80-8871-4243-bd33-5b7eb4ed53da.png)
![Screenshot (175)](https://user-images.githubusercontent.com/76481903/189813731-8d27f209-4ae8-40da-a3da-16146edc9d73.png)
![Screenshot (176)](https://user-images.githubusercontent.com/76481903/189813732-77699754-4b87-467d-b32e-3890fc1e6867.png)
