### ISSUE TITLE
Categori program dihapus

### ISSUE THREAD

**Issue by billymontolalu** [rizal1919/project-app-1#26]

**Comment by rizal1919** [comment]
![Screenshot (179)](https://user-images.githubusercontent.com/76481903/189887729-0d7d83e4-7a98-4d6f-a862-60244f7de9e5.png)
![Screenshot (180)](https://user-images.githubusercontent.com/76481903/189887738-6c5f9b61-03af-4f96-a944-abb4836d3d6e.png)
