### ISSUE TITLE
Tampilan Input Pendaftaran

### ISSUE THREAD

**Issue by billymontolalu** [rizal1919/project-app-1#3]
Ketika milih siswa itu pake dropdown search (pake select2 boostrap 5).
Setelah siswa dipilih, ktp dan data pendukung lain muncul

**Comment by rizal1919** [comment]
![Screenshot (153)](https://user-images.githubusercontent.com/76481903/186797819-f53b280d-3fc3-4dcb-b4d4-e1a56b45b418.png)
